config/routes.rb
require "sidekiq/web" # require the web UI

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"
  mount Sidekiq::Web => "/sidekiq" # access it at http://localhost:3000/sidekiq

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :boards do
    collection do
      get ":id/filter_stories", action: "filter_stories", as: "filter_stories"
    end
    resources :columns do
      resources :stories do
        collection do
          get "filter"
        end
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "boards#index"
end

app/models/column.rb
class Column < ApplicationRecord
    acts_as_paranoid
    has_paper_trail

    belongs_to :board
    has_many :stories, dependent: :destroy

    validates :title, presence: true
    validates :order, presence: true
    validates :board_id, presence: true

    def move_up
        self.order = self.order - 1
    end
    def move_down
        self.order = self.order + 1
    end
end

app/controllers/columns_controller.rb
class ColumnsController < ActionController::Base
    include Pundit::Authorization

    before_action :authenticate_user!
    before_action :set_paper_trail_whodunnit
    before_action :set_board
    before_action :set_column, only: [ :show, :edit, :update, :destroy ]

    def show
      # authorize @board
    end

    def new
        # authorize @board
        @column = @board.columns.new
      end
    def create
        # authorize @board
        creator = Columns::ColumnCreator.new
        creator.call(board: @board, params: column_params)

        if creator.successful?
            redirect_to board_column_path(@board, creator.column), notice: "Column created sucessfully"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
      # authorize @board
    end
    def update
        # authorize @board
        updater = Columns::ColumnUpdater.new
        updater.call(column: @column, params: column_params)

        if updater.successful?
            redirect_to board_column_path(@board, updater.column), notice: "Column updated successfully", status: :see_other
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        # authorize @board
        destroyer = Columns::ColumnDestroyer.new
        destroyer.call(column: @column)

        status = destroyer.successful? ? :ok : :unprocessable_entity
        redirect_to board_path(@board), notice: "Column destroyed successfully", status: :see_other
    end

    private
    def set_board
        @board = Board.find(params[:board_id])
    end
    def set_column
        @column = Column.find(params[:id])
    end
    def column_params
        params.require(:column).permit(:title, :order)
    end
end

app/views/columns/_column.html.erb
<div id="<%= dom_id column %>">
</div>

app/views/columns/_form.html.erb
<%= form_with model: [@column.board, @column], local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :order %>
    <%= form.text_field :order %>
  </div>

  <% if column.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(column.errors.count, "error") %> prohibited this column from being saved:</h2>

      <ul>
        <% column.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/columns/edit.html.erb
<% content_for :title, "Editing column" %>

<h1>Edit column: <%= @column.title %></h1>

<%= render "form", column: @column %>

<br>

<div>
  <%= button_to "Delete column", board_column_path(@column.board, @column), method: :delete %>
  <%= link_to "Back to column", board_column_path(@column.board, @column) %>
  <%= link_to "Back to board", board_path(@column.board) %>
</div>

app/views/columns/new.html.erb
<% content_for :title, "New column" %>

<h1>New column</h1>

<%= render "form", column: @column %>

<br>

<div>
  <%= link_to "Back to board", board_path(@column.board) %>
</div>

app/views/columns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @column %>

<div>
  <h1><%= @column.title %></h1>
</div>

<div>
  <%= link_to "Edit this column", edit_board_column_path(@column.board, @column) %> |
  <%= link_to "Back to board", board_path(@column.board) %>

  <%= button_to "Delete column", board_column_path(@column.board, @column), method: :delete %>
</div>

<div>
  <strong>Filter stories by: (multiple choices separated by comma)</strong>
  <%= form_with url: filter_board_column_stories_path(@column.board, @column), method: :get, local: true do |form| %>
    <div>
      <%= form.label :status %>
      <%= form.text_field :status %>
    </div>
    <div>
      <%= form.label :due_date %>
      <%= form.text_field :due_date %>
    </div>
    <div>
      <%= form.submit "Search" %>
    </div>
  <% end %>
</div>

<div>
  <strong>Stories</strong>
  <table>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Due Date</th>
    </tr>
    <% @column.stories.sort_by{|s| s[:order]}.each do |story| %>
      <tr>
        <td><%= link_to story.title, edit_board_column_story_path(@column.board, @column, story) %></td>
        <td><%= story.description %></td>
        <td><%= story.status %></td>
        <td><%= story.due_date %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to "New task", new_board_column_story_path(@column.board, @column) %>
</div>