config/routes.rb
require "sidekiq/web" # require the web UI

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"
  mount Sidekiq::Web => "/sidekiq" # access it at http://localhost:3000/sidekiq

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :boards do
    collection do
      get ":id/filter_stories", action: "filter_stories", as: "filter_stories"
    end
    resources :columns do
      resources :stories do
        collection do
          get "filter"
        end
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "boards#index"
end

app/models/story.rb
class Story < ApplicationRecord
    acts_as_paranoid
    has_paper_trail

    belongs_to :column

    validates :title, presence: true
    validates :order, presence: true
    validates :column_id, presence: true

    def move_up
        self.order = self.order - 1
    end
    def move_down
        self.order = self.order + 1
    end
end

app/controllers/stories_controller.rb
class StoriesController < ActionController::Base
    include Pundit::Authorization

    before_action :authenticate_user!
    before_action :set_paper_trail_whodunnit
    before_action :set_board
    before_action :set_column
    before_action :set_story, only: [ :edit, :update, :destroy ]

    def new
        # authorize @board
        @story = @column.stories.new
      end
    def create
        # authorize @board
        creator = Stories::StoryCreator.new
        creator.call(column: @column, params: story_params)

        if creator.successful?
            redirect_to board_column_path(@board, @column), notice: "Story created sucessfully"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
      # authorize @board
    end
    def update
        # authorize @board
        updater = Stories::StoryUpdater.new
        updater.call(story: @story, params: story_params)

        if updater.successful?
            @column = @story.column
            redirect_to board_column_path(@board, @column), notice: "Story updated successfully", status: :see_other
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        # authorize @board
        destroyer = Stories::StoryDestroyer.new
        destroyer.call(story: @story)

        status = destroyer.successful? ? :ok : :unprocessable_entity
        redirect_to board_column_path(@board, @column), notice: "Story destroyed successfully", status: :see_other
    end

    def filter
        statuses = params[:status]&.split(",") || []
        due_dates = params[:due_date]&.split(",") || []

        if !statuses.empty? && !due_dates.empty? then
            stories = @column.stories.where(status: statuses, due_date: due_dates)
        elsif !statuses.empty? then
            stories = @column.stories.where(status: statuses)
        elsif !due_dates.empty? then
            stories = @column.stories.where(due_date: due_dates)
        else stories = @column.stories
        end

        render json: stories
    end

    private
    def set_board
        @board = Board.find(params[:board_id])
    end
    def set_column
        @column = Column.find(params[:column_id])
    end
    def set_story
        @story = Story.includes(column: { board: :columns }).find(params[:id])
    end
    def story_params
        params.require(:story).permit(:title, :description, :order, :status, :due_date, :column_id)
    end
end

app/views/stories/_form.html.erb
<%= form_with model: [@story.column.board, @story.column, @story], local: true do |form| %>
  <div>
    <%= form.label :column_id %>
    <%= form.select :column_id,
      options_from_collection_for_select(@story.column.board.columns, :id, :title, @story.column_id)
    %>
  </div>
  <br>
  
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :order %>
    <%= form.text_field :order %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>
  <div>
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>
  <br>  

  <% if story.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% story.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/_story.html.erb
<div id="<%= dom_id story %>">
</div>

app/views/stories/edit.html.erb
<% content_for :title, "Editing story" %>

<h1>View/Manage Story Details</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= button_to "Delete story", board_column_story_path(@story.column.board, @story.column, @story), method: :delete %>
  <%= link_to "Back to column", board_column_path(@story.column.board, @story.column) %>
  <%= link_to "Back to board", board_path(@story.column.board) %>
</div>

app/views/stories/new.html.erb
<% content_for :title, "New story" %>

<h1>New story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Back to column", board_column_path(@story.column.board, @story.column) %>
  <%= link_to "Back to board", board_path(@story.column.board) %>
</div>