config/routes.rb
require "sidekiq/web" # require the web UI

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"
  mount Sidekiq::Web => "/sidekiq" # access it at http://localhost:3000/sidekiq

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :boards do
    collection do
      get ":id/filter_stories", action: "filter_stories", as: "filter_stories"
    end
    resources :columns do
      resources :stories do
        collection do
          get "filter"
        end
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "boards#index"
end

app/models/board.rb
class Board < ApplicationRecord
    acts_as_paranoid
    has_paper_trail

    has_many :board_permissions
    has_many :users, through: :board_permissions

    has_many :columns, dependent: :destroy
    has_many :stories, through: :columns

    validates :title, presence: true

    def count_stories
        self.stories.count
    end

    def dummy_print_column(column)
        column || "DUMMY CALL"
    end
end

app/controllers/boards_controller.rb
class BoardsController < ActionController::Base
    include Pundit::Authorization

    before_action :authenticate_user!
    before_action :set_paper_trail_whodunnit
    before_action :set_board, only: [ :show, :edit, :update, :destroy, :filter_stories ]

    def index
        if params[:showall] == "true"
            @boards = Board.includes(columns: :stories).all
            render json: @boards.map { |board| BoardPresenter.new(board).as_json({
                prettify_dates_us: true,
                board_title_upcase: true
            }) }
        else
            @boards = Board.all
        end
    end
    def show
      # authorize @board
    end

    def new
        # authorize Board
        @board = Board.new
      end
    def create
        # authorize Board
        creator = Boards::BoardCreator.new
        creator.call(params: board_params)

        if creator.successful?
            redirect_to creator.board, notice: "Board created sucessfully"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
      # authorize @board
    end
    def update
        # authorize @board
        updater = Boards::BoardUpdater.new
        updater.call(board: @board, params: board_params)

        if updater.successful?
            redirect_to updater.board, notice: "Board updated successfully", status: :see_other
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        # authorize @board
        destroyer = Boards::BoardDestroyer.new
        destroyer.call(board: @board)

        status = destroyer.successful? ? :ok : :unprocessable_entity
        redirect_to boards_path, notice: "Board destroyed successfully", status: :see_other
    end

    def filter_stories
        statuses = params[:status]&.split(",") || []
        due_dates = params[:due_date]&.split(",") || []

        stories = @board.stories

        if !statuses.empty? && !due_dates.empty? then
            stories = stories.where(status: statuses, due_date: due_dates)
        elsif !statuses.empty? then
            stories = stories.where(status: statuses)
        elsif !due_dates.empty? then
            stories = stories.where(due_date: due_dates)
        else stories = stories
        end

        render json: stories
    end

    private
    def set_board
        @board = Board.includes(columns: :stories).find(params[:id])
      end

    def board_params
        params.require(:board).permit(:title)
    end
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">
</div>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<% content_for :title, "Editing board" %>

<h1>Editing board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Show this board", @board %> |
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/index.html.erb
<div id="user"><%= render "layouts/user" %></div>

<p style="color: green"><%= notice %></p>

<% content_for :title, "Boards" %>

<%= link_to "show all data", boards_path(showall: "true") %>
<h1>Boards</h1>

<div id="boards">
  <% @boards.each do |board| %>
    <%= render board %>
    <p>
      <%= link_to board.title, board %>
    </p>
  <% end %>
</div>

<%= link_to "New board", new_board_path %>

app/views/boards/new.html.erb
<% content_for :title, "New board" %>

<h1>New board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @board %>

<div>
  <h1><%= @board.title %></h1>
</div>

<div>
  <%= link_to "Edit this board", edit_board_path(@board) %> |
  <%= link_to "Back to boards", boards_path %>

  <%= button_to "Destroy this board", @board, method: :delete %>
</div>

<div>
  <strong>Filter stories by: (multiple choices separated by comma)</strong>
  <%= form_with url: filter_stories_boards_path(@board), method: :get, local: true do |form| %>
    <div>
      <%= form.label :status %>
      <%= form.text_field :status %>
    </div>
    <div>
      <%= form.label :due_date %>
      <%= form.text_field :due_date %>
    </div>
    <div>
      <%= form.submit "Search" %>
    </div>
  <% end %>
</div>

<div>
  <ul>
    <% @board.columns.sort_by{|c| c[:order]}.each do |column| %>
      <li>
        <strong><%= link_to column.title, board_column_path(@board, column) %></strong>
        <%= link_to "edit", edit_board_column_path(@board, column) %>
        <ul>
          <% column.stories.sort_by{|s| s[:order]}.each do |story| %>
            <li><%= link_to story.title, edit_board_column_story_path(@board, column, story) %></li>
          <% end %>
          <%= link_to "New task", new_board_column_story_path(@board, column) %>
        </ul>
      </li>
    <% end %>
  </ul>
  <%= link_to "New column", new_board_column_path(@board) %>
</div>